import os
import time
import smtplib
from datetime import datetime
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import pandas as pd

from download import USE_SP500, TICKERS, get_market_context, get_sp500_tickers, safe_download
from indicator import calculate_indicators
from filter import run_filters
from score import calculate_score

VERSION = "v2.3"

# =====================================
# 掃描模式
# =====================================

def analyze_stock(ticker, market_bull, spy_return):   
    try:
        df = safe_download(ticker)
        metrics = calculate_indicators(ticker, df, spy_return)
        if metrics is None:
            return None

        passed, reason = run_filters(ticker, metrics)
        if not passed:
            return None

        score_result = calculate_score(metrics, market_bull)
       
        result = {
            "Ticker": ticker,
            **score_result,
            "RelativeStrength": round(metrics["RelativeStrength"], 2),
            "ADX": round(metrics["ADX"], 2),
            "Price": round(metrics["Price"], 2),
            "RSI": round(metrics["RSI"], 2),
            "VolumeRatio": round(metrics["VolumeRatio"], 2),
            "MA20": round(metrics["MA20"], 2),
            "MA50": round(metrics["MA50"], 2),
            "MA200": round(metrics["MA200"], 2),
            "MACD": round(metrics["MACD"], 2),
            "SignalLine": round(metrics["SignalLine"], 2),
            "MiddleBB": round(metrics["MiddleBB"], 2)
        }

        return result
    except Exception as error:
        print(f"Error processing {ticker}: {error}")
        return None

# =====================================
# Excel
# =====================================

def export_excel(df):
    today = datetime.today().strftime("%Y-%m-%d")
    filename = f"stock_scan_{today}_{VERSION}.xlsx"
    df.to_excel(filename, index=False)
    return filename

# =====================================
# Email內容
# =====================================

def build_email_body(df, market_bull, spy_price, spy_ma200):
    market_status = "🟢 BULL" if market_bull else "🔴 BEAR"
    body = f"""
================================
US STOCK SCANNER {VERSION}

Market:
{market_status}

SPY:
{spy_price:.2f}

SPY MA200:
{spy_ma200:.2f}
================================

Top Candidates:
"""

    for _, row in df.iterrows():
        body += f"""
Rank: {row.get('R', '')}
Ticker: {row['Ticker']}
Signal: {row['Signal']}
Score: {row['Score']}
Price: {row['Price']}
RSI: {row['RSI']}
Volume Ratio: {row['VolumeRatio']}
Relative Strength: {row['RelativeStrength']}
ADX: {row['ADX']}
-------------------
"""

    body += "\nGenerated by GitHub Actions"
    return body

# =====================================
# Send Email
# =====================================

def send_email(subject, body, attachment=None):
    email_user = os.environ["EMAIL_USER"]
    email_password = os.environ["EMAIL_PASSWORD"]
    email_to = os.environ["EMAIL_TO"]

    msg = MIMEMultipart()
    msg["From"] = email_user
    msg["To"] = email_to
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))
    
    if attachment:
        with open(attachment, "rb") as file:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(file.read())
        encoders.encode_base64(part)
        part.add_header("Content-Disposition", f"attachment; filename={attachment}")
        msg.attach(part)

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(email_user, email_password)
        server.send_message(msg)

    print("Email sent successfully")

# ==========================
# BEAR MARKET PROTECTION
# ==========================

def send_bear_market_email(spy_price, spy_ma200):
        body = f"""
MARKET STATUS
🔴 BEAR

SPY:
{spy_price:.2f}

SPY MA200:
{spy_ma200:.2f}

No swing trades today.
"""
        send_email(f"🔴 Bear Market Alert US Scanner {VERSION}", body, None)

def send_no_candidates_email(market_bull, spy_price, spy_ma200):
        body = f"""
MARKET STATUS
{"BULL" if market_bull else "🔴 BEAR"}

SPY:
{spy_price}

SPY MA200:
{spy_ma200}

No stocks passed analysis. Filters or scoring may be too strict.
"""
        send_email(f"No Candidates US Scanner {VERSION} Top20", body, None)

# =====================================
# Main
# =====================================

def main():
    print(f"Scanning stocks with US Stock Scanner {VERSION}...")
    results = []

    # ==========================
    # LOAD DATA
    # ==========================

    if USE_SP500:
        tickers = get_sp500_tickers()
        print(f"Loaded {len(tickers)} S&P500 stocks")
        market = get_market_context()
        spy_price = market["spy_price"]
        spy_ma200 = market["spy_ma200"]
        spy_return = market["spy_return"]
        market_bull = market["market_bull"]
        print(f"Market Bull: {market_bull}")
    else:
        print("TEST MODE ENABLED")
        tickers = TICKERS
        spy_price = 0
        spy_ma200 = 0
        spy_return = 0
        market_bull = True

    # ==========================
    # BEAR MARKET
    # ==========================
    
    if spy_price is not None and spy_ma200 is not None and spy_price < spy_ma200:
        print("Bear market detected")
        send_bear_market_email(spy_price, spy_ma200)
        return
    
    # ==========================
    # SCAN LOOP
    # ==========================

    for ticker in tickers:
        print(f"Processing {ticker}")
        result = analyze_stock(ticker, market_bull, spy_return)
        if result:
            print(f"{ticker} scored: {result['Score']:.2f}")
            results.append(result)
        else:
            print(f"{ticker} filtered out")
        time.sleep(0.2)

    # ==========================
    # NO CANDIDATES
    # ==========================

    if len(results) == 0:
        send_no_candidates_email(market_bull, spy_price, spy_ma200)
        return

    # ==========================
    # DATAFRAME
    # ==========================

    df = pd.DataFrame(results).sort_values(by="Score", ascending=False)

    # ==========================
    # TOP 20 FIX (IMPORTANT)
    # ==========================
    
    top20 = df.head(20).copy()
    top20.insert(0, "Rank", range(1, len(top20) + 1))

    print("\nTOP 20 RESULTS:")
    print(top20[["Rank", "Ticker", "Score", "Signal"]])
    print(f"\nPassed stocks: {len(df)}")

    # ==========================
    # EXPORT
    # ==========================

    excel_file = export_excel(top20)
    email_body = build_email_body(top20, market_bull, spy_price, spy_ma200)
    send_email(f"📈 US Scanner {VERSION} Daily Top 20", email_body, excel_file)

if __name__ == "__main__":
    main()
